name: Docker Build and Apiiro Scan

on:
  workflow_dispatch:


jobs:
  docker-build:
    name: Apiiro BuildScan
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2


  apiiro-scan:
    name: Apiiro Build Scan
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Apiiro API Build Scan
      run: |
        response=$(curl -s --location 'https://app-staging.apiiro.com/rest-api/v1/buildScan/builds' \
              --header 'Content-Type: application/json' \
              --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}' \
              --data '{
                "commitSha": "${{ github.sha }}",
                "repositoryUrl": "https://github.com/${{ github.repository }}",
                "buildId": "${{ github.run_id }}"
              }')
        echo "Trigger response: $response"
        scan_id=$(echo "$response" | jq -r '.id // .')
        echo "Scan ID: $scan_id"
        echo "SCAN_ID=$scan_id" >> $GITHUB_ENV

    - name: Apiiro API Results Scan
      run: |
        max_retries=20
        current_retry=0
        echo "Starting Apiiro API Results Scan..."

        while true; do
            echo "Attempt: $current_retry of $max_retries"
            response=$(curl -sS --insecure --retry 3 --location --request GET "https://app-staging.apiiro.com/rest-api/v2/buildScan/${{ env.SCAN_ID }}/results" \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.BEARER_TOKEN }}')

            if ! echo "$response" | jq empty 2>/dev/null; then
                echo "Received an invalid JSON response. Waiting before the next check..."
            else
                echo "API Response Summary:"
                echo "$response" | jq -r '.summary'
                echo "---------------------"
                echo "API Scan Results:"
                if echo "$response" | jq -e '.scanResults' >/dev/null 2>&1; then
                    echo "$response" | jq -r '.scanResults[]'
                else
                    echo "No scan results available."
                fi
                echo "---------------------"

                if echo "$response" | jq -e '.buildPassed' 2>/dev/null | grep -q "true"; then
                    echo "Pipeline can continue. Apiiro scan passed."
                    exit 0
                elif echo "$response" | jq -e '.buildPassed' 2>/dev/null | grep -q "false"; then
                    echo "Apiiro scan failed. Blocking pipeline."
                    exit 1
                else
                    echo "Scan not yet complete, waiting..."
                fi
            fi

            ((current_retry++))
            if [[ $current_retry -ge $max_retries ]]; then
                echo "Max retries reached without a conclusive result. Exiting."
                exit 1
            fi

            sleep 30
        done
